<a href="https://colab.research.google.com/github/Ans365332/6may-file-example/blob/main/Deep_Learning_2(ANN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [61]:
df=pd.read_csv('/content/Attrition - Attrition.csv')
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [21]:
import tensorflow as trf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score

In [62]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [63]:
df=df.dropna()

In [64]:
x= df.drop(columns=['Attrition'])
y=df['Attrition']

In [65]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 34 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   BusinessTravel            1470 non-null   object
 2   DailyRate                 1470 non-null   int64
 3   Department                1470 non-null   object
 4   DistanceFromHome          1470 non-null   int64
 5   Education                 1470 non-null   int64
 6   EducationField            1470 non-null   object
 7   EmployeeCount             1470 non-null   int64
 8   EmployeeNumber            1470 non-null   int64
 9   EnvironmentSatisfaction   1470 non-null   int64
 10  Gender                    1470 non-null   object
 11  HourlyRate                1470 non-null   int64
 12  JobInvolvement            1470 non-null   int64
 13  JobLevel                  1470 non-null   int64
 14  JobRole                   1470 non-null   object
 15  JobSatisfaction           1470 non-null   int64
 16  MaritalStatus             1470 non-null   object
 17  MonthlyIncome             1470 non-null   int64
 18  MonthlyRate               1470 non-null   int64
 19  NumCompaniesWorked        1470 non-null   int64
 20  Over18                    1470 non-null   object
 21  OverTime                  1470 non-null   object
 22  PercentSalaryHike         1470 non-null   int64
 23  PerformanceRating         1470 non-null   int64
 24  RelationshipSatisfaction  1470 non-null   int64
 25  StandardHours             1470 non-null   int64
 26  StockOptionLevel          1470 non-null   int64
 27  TotalWorkingYears         1470 non-null   int64
 28  TrainingTimesLastYear     1470 non-null   int64
 29  WorkLifeBalance           1470 non-null   int64
 30  YearsAtCompany            1470 non-null   int64
 31  YearsInCurrentRole        1470 non-null   int64
 32  YearsSinceLastPromotion   1470 non-null   int64
 33  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(8)
memory usage: 390.6+ KB

In [66]:
categorical_features = ['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'OverTime','Over18']

In [67]:
x_encoded = pd.get_dummies(x, columns=categorical_features,
                           drop_first= True)

In [68]:
x_encoded = x_encoded.astype(int)

In [69]:
x_encoded

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0,0,0,0,0,1,0,0,1,1
1,49,279,8,1,1,2,3,61,2,2,...,0,0,0,0,1,0,0,1,0,0
2,37,1373,2,2,1,4,4,92,2,1,...,1,0,0,0,0,0,0,0,1,1
3,33,1392,3,4,1,5,4,56,3,1,...,0,0,0,0,1,0,0,1,0,1
4,27,591,2,1,1,7,1,40,3,1,...,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,884,23,2,1,2061,3,41,4,2,...,1,0,0,0,0,0,0,1,0,0
1466,39,613,6,1,1,2062,4,42,2,3,...,0,0,0,0,0,0,0,1,0,0
1467,27,155,4,3,1,2064,2,87,4,2,...,0,0,1,0,0,0,0,1,0,1
1468,49,1023,2,3,1,2065,4,63,2,2,...,0,0,0,0,0,1,0,1,0,0
1469,34,628,8,3,1,2068,2,82,4,2,...,1,0,0,0,0,0,0,1,0,0

In [70]:
# encoded target data
lb= LabelEncoder()

In [71]:
y_encoded = lb.fit_transform(y)
y_encoded

array([1, 0, 1, ..., 0, 0, 0])

In [72]:
x_train, x_test, y_train, y_test = train_test_split(x_encoded, y_encoded, test_size = 0.2,
                                                    random_state =42)

In [73]:
x_train.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
1097,24,350,21,2,1,1551,3,57,2,1,...,1,0,0,0,0,0,0,0,0,0
727,18,287,5,2,1,1012,2,73,3,1,...,0,0,0,0,1,0,0,0,1,0
254,29,1247,20,2,1,349,4,45,3,2,...,0,0,0,0,0,1,0,0,0,0
1175,39,492,12,3,1,1654,4,66,3,2,...,0,0,1,0,0,0,0,1,0,0
1341,31,311,20,3,1,1881,2,89,3,2,...,1,0,0,0,0,0,0,0,0,0

In [74]:
sc = StandardScaler()

In [75]:
x_train_scaled = sc.fit_transform(x_train)
x_test_scaled = sc.transform(x_test)

In [76]:
# Now we will create architecture of our model

In [77]:
model = trf.keras.models.Sequential([
    trf.keras.layers.Dense(units = 128, activation='relu',
                          input_dim = x_train_scaled.shape[1]),  # input layer
    trf.keras.layers.Dropout(0.3),
    trf.keras.layers.Dense(units = 64, activation='relu'), # hidden layer
    trf.keras.layers.Dropout(0.3),
    trf.keras.layers.Dense(units =1 , activation='sigmoid') # output layer
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [78]:
# compile the model

In [79]:
loss_fn = trf.keras.losses.BinaryCrossentropy()
metrics = ['accuracy']

In [80]:
learning_rate = 0.001
momentum = 0.9
optimizer = trf.keras.optimizers.SGD(learning_rate=learning_rate, momentum=momentum,
                                     nesterov=True)

In [81]:
model.compile(optimizer = optimizer , loss = loss_fn ,metrics = metrics)

In [82]:
# Train the model

In [83]:
model.fit(x_train_scaled,
          y_train,
          epochs = 50,
          batch_size = 8,
          validation_split = 0.1)

Epoch 1/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7382 - loss: 0.5741 - val_accuracy: 0.7966 - val_loss: 0.4994
Epoch 2/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8374 - loss: 0.4391 - val_accuracy: 0.7966 - val_loss: 0.4634
Epoch 3/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8422 - loss: 0.4178 - val_accuracy: 0.7966 - val_loss: 0.4466
Epoch 4/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8507 - loss: 0.3909 - val_accuracy: 0.8051 - val_loss: 0.4321
Epoch 5/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8563 - loss: 0.3858 - val_accuracy: 0.8220 - val_loss: 0.4231
Epoch 6/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8573 - loss: 0.3758 - val_accuracy: 0.8220 - val_loss: 0.4158
Epoch 7/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8592 - loss: 0.3490 - val_accuracy: 0.8390 - val_loss: 0.4045
Epoch 8/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8620 - loss: 0.3551 - val_accuracy: 0.8305 - val_loss: 0.4004
Epoch 9/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8743 - loss: 0.3415 - val_accuracy: 0.8475 - val_loss: 0.3957
Epoch 10/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8743 - loss: 0.3204 - val_accuracy: 0.8475 - val_loss: 0.3924
Epoch 11/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8781 - loss: 0.3114 - val_accuracy: 0.8475 - val_loss: 0.3927
Epoch 12/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8648 - loss: 0.3267 - val_accuracy: 0.8390 - val_loss: 0.3900
Epoch 13/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8913 - loss: 0.3160 - val_accuracy: 0.8305 - val_loss: 0.3912
Epoch 14/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8847 - loss: 0.2991 - val_accuracy: 0.8390 - val_loss: 0.3976
Epoch 15/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8762 - loss: 0.2950 - val_accuracy: 0.8305 - val_loss: 0.3942
Epoch 16/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8970 - loss: 0.2843 - val_accuracy: 0.8305 - val_loss: 0.3942
Epoch 17/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8743 - loss: 0.2959 - val_accuracy: 0.8220 - val_loss: 0.3958
Epoch 18/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9026 - loss: 0.2767 - val_accuracy: 0.8220 - val_loss: 0.3968
Epoch 19/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8762 - loss: 0.2743 - val_accuracy: 0.8220 - val_loss: 0.3962
Epoch 20/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8951 - loss: 0.2768 - val_accuracy: 0.8220 - val_loss: 0.3949
Epoch 21/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8875 - loss: 0.2668 - val_accuracy: 0.8220 - val_loss: 0.3980
Epoch 22/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8951 - loss: 0.2736 - val_accuracy: 0.8220 - val_loss: 0.3949
Epoch 23/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9008 - loss: 0.2614 - val_accuracy: 0.8305 - val_loss: 0.3968
Epoch 24/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8970 - loss: 0.2520 - val_accuracy: 0.7966 - val_loss: 0.3966
Epoch 25/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9064 - loss: 0.2496 - val_accuracy: 0.8220 - val_loss: 0.4033
Epoch 26/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8960 - loss: 0.2546 - val_accuracy: 0.8305 - val_loss: 0.4081
Epoch 27/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8885 - loss: 0.2564 - val_accuracy: 0.8220 - val_loss: 0.4046
Epoch 28/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9026 - loss: 0.2450 - val_accuracy: 0.8136 - val_loss: 0.4095
Epoch 29/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8951 - loss: 0.2374 - val_accuracy: 0.8220 - val_loss: 0.4131
Epoch 30/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9112 - loss: 0.2328 - val_accuracy: 0.8051 - val_loss: 0.4053
Epoch 31/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9045 - loss: 0.2409 - val_accuracy: 0.8136 - val_loss: 0.4072
Epoch 32/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9064 - loss: 0.2337 - val_accuracy: 0.8220 - val_loss: 0.4127
Epoch 33/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9064 - loss: 0.2344 - val_accuracy: 0.8220 - val_loss: 0.4186
Epoch 34/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9149 - loss: 0.2286 - val_accuracy: 0.8220 - val_loss: 0.4270
Epoch 35/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9074 - loss: 0.2379 - val_accuracy: 0.8136 - val_loss: 0.4227
Epoch 36/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9083 - loss: 0.2248 - val_accuracy: 0.8220 - val_loss: 0.4208
Epoch 37/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9045 - loss: 0.2301 - val_accuracy: 0.8051 - val_loss: 0.4196
Epoch 38/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9197 - loss: 0.2125 - val_accuracy: 0.8051 - val_loss: 0.4204
Epoch 39/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9159 - loss: 0.2169 - val_accuracy: 0.8220 - val_loss: 0.4297
Epoch 40/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9206 - loss: 0.2092 - val_accuracy: 0.8220 - val_loss: 0.4294
Epoch 41/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9149 - loss: 0.2135 - val_accuracy: 0.8051 - val_loss: 0.4285
Epoch 42/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9140 - loss: 0.2072 - val_accuracy: 0.8051 - val_loss: 0.4356
Epoch 43/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9187 - loss: 0.2017 - val_accuracy: 0.8136 - val_loss: 0.4293
Epoch 44/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9225 - loss: 0.1981 - val_accuracy: 0.8136 - val_loss: 0.4313
Epoch 45/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9282 - loss: 0.1981 - val_accuracy: 0.8220 - val_loss: 0.4355
Epoch 46/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9187 - loss: 0.1864 - val_accuracy: 0.8136 - val_loss: 0.4487
Epoch 47/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9225 - loss: 0.2011 - val_accuracy: 0.8051 - val_loss: 0.4495
Epoch 48/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9197 - loss: 0.1995 - val_accuracy: 0.8136 - val_loss: 0.4542
Epoch 49/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9206 - loss: 0.1806 - val_accuracy: 0.7966 - val_loss: 0.4576
Epoch 50/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9272 - loss: 0.1918 - val_accuracy: 0.8136 - val_loss: 0.4602

In [84]:
# model total loss and total accuracy
loss , accuracy_score = model.evaluate(x_test_scaled, y_test)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8810 - loss: 0.3645

In [85]:
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy_score:.4f}")

Test Loss: 0.3645
Test Accuracy: 0.8810

# on covid data

In [86]:
df=pd .read_csv('/content/covid_toy - covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [88]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [89]:
df['fever']=df['fever'].fillna(df['fever'].mean())

In [90]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [91]:
lb= LabelEncoder()

In [92]:
df['city']=lb.fit_transform(df['city'])
df['cough']=lb.fit_transform(df['cough'])
df['gender']=lb.fit_transform(df['gender'])
df['has_covid']=lb.fit_transform(df['has_covid'])

In [93]:
df.head()

   age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0
3   31       0   98.0      0     2          0
4   65       0  101.0      0     3          0

In [94]:
x=df.drop(columns=['has_covid'])
y=df['has_covid']

In [96]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size =0.2,random_state = 42)

In [97]:
sc= StandardScaler()

In [98]:
x_train_scaled = sc.fit_transform(x_train)
x_test_scaled = sc.transform(x_test)

In [99]:
model = trf.keras.models.Sequential([
    trf.keras.layers.Dense(units = 128, activation='relu',
                          input_dim = x_train_scaled.shape[1]),  # input layer
    trf.keras.layers.Dropout(0.3),
    trf.keras.layers.Dense(units = 64, activation='relu'), # hidden layer
    trf.keras.layers.Dropout(0.3),
    trf.keras.layers.Dense(units =1 , activation='sigmoid') # output layer
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [100]:
loss_fn = trf.keras.losses.BinaryCrossentropy()
metrics = ['accuracy']

In [101]:
learning_rate = 0.001
momentum = 0.9
optimizer = trf.keras.optimizers.SGD(learning_rate=learning_rate,momentum=momentum,nesterov=True)

In [102]:
model.compile(optimizer = optimizer , loss = loss_fn ,metrics = metrics)

In [103]:
model.fit(x_train_scaled,
          y_train,
          epochs = 50,
          batch_size = 8,
          validation_split = 0.1)

Epoch 1/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 97ms/step - accuracy: 0.5139 - loss: 0.7187 - val_accuracy: 0.5000 - val_loss: 0.7175
Epoch 2/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.4861 - loss: 0.7370 - val_accuracy: 0.5000 - val_loss: 0.7141
Epoch 3/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.4306 - loss: 0.7308 - val_accuracy: 0.5000 - val_loss: 0.7103
Epoch 4/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.4306 - loss: 0.7210 - val_accuracy: 0.5000 - val_loss: 0.7072
Epoch 5/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4722 - loss: 0.7037 - val_accuracy: 0.3750 - val_loss: 0.7043
Epoch 6/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5000 - loss: 0.7028 - val_accuracy: 0.3750 - val_loss: 0.7016
Epoch 7/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5000 - loss: 0.6888 - val_accuracy: 0.5000 - val_loss: 0.6999
Epoch 8/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.4861 - loss: 0.7085 - val_accuracy: 0.5000 - val_loss: 0.6983
Epoch 9/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5556 - loss: 0.6887 - val_accuracy: 0.5000 - val_loss: 0.6970
Epoch 10/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.4722 - loss: 0.6954 - val_accuracy: 0.3750 - val_loss: 0.6963
Epoch 11/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4861 - loss: 0.7065 - val_accuracy: 0.5000 - val_loss: 0.6956
Epoch 12/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5833 - loss: 0.6808 - val_accuracy: 0.5000 - val_loss: 0.6953
Epoch 13/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.4167 - loss: 0.6961 - val_accuracy: 0.5000 - val_loss: 0.6948
Epoch 14/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6767 - val_accuracy: 0.5000 - val_loss: 0.6940
Epoch 15/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6111 - loss: 0.6679 - val_accuracy: 0.5000 - val_loss: 0.6934
Epoch 16/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5139 - loss: 0.6840 - val_accuracy: 0.5000 - val_loss: 0.6925
Epoch 17/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5556 - loss: 0.6894 - val_accuracy: 0.5000 - val_loss: 0.6929
Epoch 18/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5278 - loss: 0.7133 - val_accuracy: 0.5000 - val_loss: 0.6930
Epoch 19/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5972 - loss: 0.6721 - val_accuracy: 0.5000 - val_loss: 0.6926
Epoch 20/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5694 - loss: 0.6902 - val_accuracy: 0.5000 - val_loss: 0.6926
Epoch 21/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6389 - loss: 0.6671 - val_accuracy: 0.5000 - val_loss: 0.6930
Epoch 22/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5972 - loss: 0.6786 - val_accuracy: 0.5000 - val_loss: 0.6929
Epoch 23/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.4306 - loss: 0.7214 - val_accuracy: 0.5000 - val_loss: 0.6921
Epoch 24/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5972 - loss: 0.6785 - val_accuracy: 0.5000 - val_loss: 0.6919
Epoch 25/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6528 - loss: 0.6643 - val_accuracy: 0.5000 - val_loss: 0.6912
Epoch 26/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6111 - loss: 0.6599 - val_accuracy: 0.6250 - val_loss: 0.6904
Epoch 27/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5972 - loss: 0.6787 - val_accuracy: 0.5000 - val_loss: 0.6902
Epoch 28/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5694 - loss: 0.6847 - val_accuracy: 0.5000 - val_loss: 0.6904
Epoch 29/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5833 - loss: 0.6857 - val_accuracy: 0.5000 - val_loss: 0.6907
Epoch 30/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7361 - loss: 0.6645 - val_accuracy: 0.5000 - val_loss: 0.6905
Epoch 31/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5694 - loss: 0.6948 - val_accuracy: 0.6250 - val_loss: 0.6907
Epoch 32/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5972 - loss: 0.6799 - val_accuracy: 0.6250 - val_loss: 0.6903
Epoch 33/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.6951 - val_accuracy: 0.6250 - val_loss: 0.6904
Epoch 34/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5417 - loss: 0.6718 - val_accuracy: 0.6250 - val_loss: 0.6908
Epoch 35/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5694 - loss: 0.6820 - val_accuracy: 0.6250 - val_loss: 0.6904
Epoch 36/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5556 - loss: 0.6959 - val_accuracy: 0.6250 - val_loss: 0.6901
Epoch 37/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.6628 - val_accuracy: 0.6250 - val_loss: 0.6898
Epoch 38/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6389 - loss: 0.6721 - val_accuracy: 0.6250 - val_loss: 0.6898
Epoch 39/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6389 - loss: 0.6686 - val_accuracy: 0.6250 - val_loss: 0.6894
Epoch 40/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5833 - loss: 0.6903 - val_accuracy: 0.6250 - val_loss: 0.6896
Epoch 41/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6111 - loss: 0.6769 - val_accuracy: 0.6250 - val_loss: 0.6903
Epoch 42/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5972 - loss: 0.6903 - val_accuracy: 0.6250 - val_loss: 0.6904
Epoch 43/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6806 - loss: 0.6448 - val_accuracy: 0.6250 - val_loss: 0.6904
Epoch 44/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6111 - loss: 0.6710 - val_accuracy: 0.6250 - val_loss: 0.6903
Epoch 45/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6389 - loss: 0.6727 - val_accuracy: 0.6250 - val_loss: 0.6911
Epoch 46/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6111 - loss: 0.6561 - val_accuracy: 0.6250 - val_loss: 0.6913
Epoch 47/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6250 - loss: 0.6570 - val_accuracy: 0.6250 - val_loss: 0.6919
Epoch 48/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6389 - loss: 0.6547 - val_accuracy: 0.5000 - val_loss: 0.6924
Epoch 49/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6389 - loss: 0.6716 - val_accuracy: 0.6250 - val_loss: 0.6923
Epoch 50/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5556 - loss: 0.6806 - val_accuracy: 0.6250 - val_loss: 0.6923

In [104]:
# model total loss and total accuracy
loss , accuracy_score = model.evaluate(x_test_scaled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step - accuracy: 0.7000 - loss: 0.6545

In [105]:
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy_score:.4f}")

Test Loss: 0.6545
Test Accuracy: 0.7000

In [ ]:
# in this to minimize the loss we have to try to change three points
#. optimizer
#. epochs
#. batch_size