<a href="https://colab.research.google.com/github/Ans365332/6may-file-example/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas as pd

In [8]:
df= pd.read_csv("/content/IMDB Dataset - IMDB Dataset.csv")

In [9]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [10]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

#Step-1 --> Lowercasing

In [11]:
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [12]:
# If i want to convert all movie review into lowercase then

df['review'] = df['review'].str.lower()

In [13]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

#Step-2--> Remove Html tags

In [14]:
import re #regular expression
def remove_html_tags(text):
  pattern=re.compile('<.*?>')
  return pattern.sub(r'',text)

In [15]:
text= "<html><body><p> Movie1 </p><p> Actor - Aamir Khan </p><p> Click here to <a href='http://google.com'>download</a></p></body></html>"

In [16]:
remove_html_tags(text)

' Movie1  Actor - Aamir Khan  Click here to download'

In [17]:
# now we remove tags from IMBD datasets
df['review']=df['review'].apply(remove_html_tags)

In [18]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

#Step-3 --> Remove Url

In [19]:
# If i want to remove urls from text then

def remove_url(text):
  pattern=re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'',text)

In [20]:
text2='For notebook click https://www.deture.com/delta/note1234acc'

In [21]:
remove_url(text2)

'For notebook click '

In [22]:
df['review']=df['review'].apply(remove_url)

#Step-4 --> Remove Punctuation

In [23]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [24]:
exclude=string.punctuation

In [25]:
def remove_punc(text):
  for char in exclude:
    text=text.replace(char,'')
  return text

In [26]:
text3= 'string. with. Punctuation?'

In [27]:
remove_punc(text3)

'string with Punctuation'

In [28]:
df['review']=df['review'].apply(remove_punc)

In [29]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

# Step-5--> Chatword Treatment

In [30]:
chat_words ={'u2': 'you too', 'BBL':'Be Back Later','GAL':'Get A Life'}

In [31]:
chat_words

{'u2': 'you too', 'BBL': 'Be Back Later', 'GAL': 'Get A Life'}

In [32]:
def chat_conversation(text):
  new_text = []
  for w in text.split():
    if w.upper() in chat_words:
      new_text.append(chat_words[w.upper()])
    else:
      new_text.append(w)
  return " ".join(new_text)

In [33]:
chat_conversation('BBL')

'Be Back Later'

# Step-6--> Spelling Correction

In [34]:
from textblob import TextBlob

In [35]:
incorrect_text = "ceertain conditionas duriing seveal ggenerations aree moodified in the saame maner."

textBlb = TextBlob(incorrect_text)

textBlb.correct().string

'certain conditions during several generations are modified in the same manner.'

# Step-7 Removing Stepwords

In [36]:
import nltk # natural language tool kit
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [37]:
STOPWORDS = set(stopwords.words('english'))

In [38]:
#STOPWORDS

In [39]:
# manually work
def remove_stopwords(text):
  new_text =[]
  for word in text.split():
    if word in set(stopwords.words('english')):
      new_text.append('')
    else:
      new_text.append(word)
  x=new_text[:]
  new_text.clear()
  return " ".join(x)

In [40]:
remove_stopwords('probably my all-time favorite movie , a story of selflessness,sacrifice and dedication')

'probably  all-time favorite movie ,  story  selflessness,sacrifice  dedication'

# Tokenization

In [41]:
# 1. prefix - character(s) at the begining =$(" .)
# 2. suffix - character(s) at the end =km).!"
# 3. Infix - character(s) in between = --/....
# 4. Exception - special-case rule to split a string into several tokens or a single token or
#               prevent a token from being split when punctuation rules are applied . = let's U.s.

In [42]:
# Approach the tokenization using the split function
# 1. word tokenization

sent1 = "I am going to delhi"
sent1.split()

['I', 'am', 'going', 'to', 'delhi']

In [43]:
# sentence tokenization
sent2 = "I am going to delhi. I will stay there for 3 days. Let\'s hope the trip to be great"
sent2.split('.')

['I am going to delhi',
 ' I will stay there for 3 days',
 " Let's hope the trip to be great"]

In [44]:
# Problems with split function
sent3 = "I am going to delhi!"
sent3.split()

['I', 'am', 'going', 'to', 'delhi!']

# 1.NLTK

In [45]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [46]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [47]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [48]:
sent1 = " I am going to visit delhi!"
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'visit', 'delhi', '!']

In [49]:
sent2 = "I have a Ph.D. in A.I."
sent3 = "We are here to help! mail us at nks@gmail.com"
sent4 = "A 5km ride cost $10.50"

In [50]:
word_tokenize(sent2)

['I', 'have', 'a', 'Ph.D.', 'in', 'A.I', '.']

In [51]:
sent_tokenize(sent3)

['We are here to help!', 'mail us at nks@gmail.com']

# Stemming

In [52]:
# 1. Inflection ==> "In grammer, inflection is the modification of a word
# to express differrent grammatical categories such as tense , case , voice,
# aspect ,person , number , gender and mood"


# 2.Stemming ==> Stemming is the process of reducing inflecton in words to
# their root forms such as mapping a group of words to the same stem even if
# the stem itself is not a valid word in the language.

In [53]:
from nltk.stem.porter import PorterStemmer

In [54]:
ps = PorterStemmer()
def stem_words(text):
  return " ".join([ps.stem(word) for word in text.split()])

In [55]:
sample = "walk walks walking walked"
stem_words(sample)

'walk walk walk walk'

In [56]:
# stemming mapping a group of words to the same stem even if the stem itself
# is not valid word in language . so , this is the big issue of stemming


text = 'Probably my alltime favourite movie a story of selflessness sacrifise and dedication'
print(text)

Probably my alltime favourite movie a story of selflessness sacrifise and dedication

In [57]:
stem_words(text)

'probabl my alltim favourit movi a stori of selfless sacrifis and dedic'

In [58]:
# so , we have to use lemmatization instead of stemming
# note - stemming is fast and lemmatization is slow

In [59]:
# Lemmatization , unlike stemming , reduces the inflected words properly
# ensuring that
# the root word belongs to the language.
# In lemmatization root word is called Lemma .
# Alemma(plural Lemmas or Lemmata) is the canonical form , dictionary form,
# or citation form of a set of words .config/


# stemming works on behalf of algorithm , so it is fast and Lemmatization is
# using wordnet package , so it is slow.

In [60]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [61]:

wordnet_lemmatizer = WordNetLemmatizer()
#

In [62]:
from nltk.tokenize.sonority_sequencing import punctuation
sentence = "He was running and eating at the same time . He has a bad habbit of swimming afte playing long hours in the sun"

punctuation='?:!.,;'
sentence_words = nltk.word_tokenize(sentence)
for word in sentence_words:
  sentence_words.remove(word)

sentence_words
print("{0:20}{1:20}".format("Word","Lemma"))
for word in sentence_words:
  print("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word)))

Word                Lemma
was                 wa
and                 and
at                  at
same                same
.                   .
has                 ha
bad                 bad
of                  of
afte                afte
long                long
in                  in
sun                 sun

# Text Representation

In [ ]:
# 1. Bag of words(bow)
# we use countvectorization

In [64]:
import numpy as np
import pandas as pd

In [66]:
df=pd.DataFrame({'text':['people watch cricket',
                         'player was player',
                         'people write comment',
                         'cricket play comment'],
                 'output':[1,1,0,0]})

In [67]:
df

                   text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [ ]:
# people watch cricket player was write comment play

# [11100000]
# [00021000]
# [10000110]
# [00100011]

In [68]:
from sklearn.feature_extraction.text import CountVectorizer

In [69]:
cv = CountVectorizer()

In [70]:
bow = cv.fit_transform(df['text'])

In [71]:
# vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 6, 'cricket': 1, 'player': 4, 'was': 5, 'write': 7, 'comment': 0, 'play': 3}

In [72]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 0 0 0 1 0]]
[[0 0 0 0 2 1 0 0]]

In [73]:
cv.transform(["cricket watch and write comment of cricket comment"]).toarray()

array([[2, 2, 0, 0, 0, 0, 1, 1]])

In [74]:
# 2.N-grams

In [75]:
v = CountVectorizer(ngram_range=(1,2))
# v = CountVectorizer(ngram_range=(2,2))

In [76]:
bow = v.fit_transform(df['text'])

In [77]:
df['text']

0    people watch cricket
1       player was player
2    people write comment
3    cricket play comment
Name: text, dtype: object

In [78]:
# vocab
print(v.vocabulary_)

{'people': 3, 'watch': 12, 'cricket': 1, 'people watch': 4, 'watch cricket': 13, 'player': 8, 'was': 10, 'player was': 9, 'was player': 11, 'write': 14, 'comment': 0, 'people write': 5, 'write comment': 15, 'play': 6, 'cricket play': 2, 'play comment': 7}

In [ ]:
# Tf(Term Frequency)
# 2.  IDF(Inverse Document Frequency)

In [ ]:
# TF(t,d) = (Number of occurences of term t in document d)/
# (Total number of terms in the document d)
# example ===>
# d1 = people watch cricket

# tf(people,d1) = 1/3

# d2 = match was match
# tf(match , d2) = 2/3

In [ ]:
# IDF(t) = Large(Total number of documents in the corpus)/
# (Number of documents with term t in them)
# here corpus means number of sentences


# Example ==>
# d1 = people watch cricket
# d2 = cricket was cricket
# d3 = people write comment
# d4 = cricket write comment

# idf(cricket) = log(4/4)
# idf(people) = log(4/2)

In [ ]:
# we can use this by apply feature_extraction method in sklearn

In [79]:
df

                   text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [80]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.52640543, 0.52640543, 0.        , 0.        ,
        0.        , 0.66767854, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.89442719,
        0.4472136 , 0.        , 0.        ],
       [0.52640543, 0.        , 0.52640543, 0.        , 0.        ,
        0.        , 0.        , 0.66767854],
       [0.52640543, 0.52640543, 0.        , 0.66767854, 0.        ,
        0.        , 0.        , 0.        ]])

In [81]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073]
['comment' 'cricket' 'people' 'play' 'player' 'was' 'watch' 'write']